# Generated by Django 6.0.5 on 2026-08-16 14:13

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdHabitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
                ('use_yn', models.CharField(default='Y', max_length=2)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdHabitItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
                ('use_yn', models.CharField(default='Y', max_length=2)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdHabitItemDetailTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.CharField(choices=[('MON', '월'), ('TUE', '화'), ('WED', '수'), ('THU', '목'), ('FRI', '금'), ('SAT', '토'), ('SUN', '일')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_day', models.CharField(choices=[('MON', '월'), ('TUE', '화'), ('WED', '수'), ('THU', '목'), ('FRI', '금'), ('SAT', '토'), ('SUN', '일')], max_length=3)),
                ('end_time', models.TimeField()),
                ('use_yn', models.CharField(default='Y', max_length=2)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField()),
                ('use_yn', models.CharField(default='Y', max_length=2)),
                ('notice_yn', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file', models.ManyToManyField(related_name='file_thirdHabit', to='common.file')),
                ('viewcount', models.ManyToManyField(related_name='viewcount_thirdHabit', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ManyToManyField(related_name='voter_thirdHabit', to=settings.AUTH_USER_MODEL)),
                ('item', models.ManyToManyField(related_name='item_thirdHabit', to='thirdHabit.thirdhabititem')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdHabitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
                ('use_yn', models.CharField(default='Y', max_length=2)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thirdHabit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdHabit.thirdhabit')),
            ],
        ),
        migrations.AddField(
            model_name='thirdhabititem',
            name='detailItem',
            field=models.ManyToManyField(related_name='detailItem_thirdHabit', to='thirdHabit.thirdhabititemdetail'),
        ),
        migrations.AddField(
            model_name='thirdhabititemdetail',
            name='detailTimeItem',
            field=models.ManyToManyField(related_name='detailTimeItem_thirdHabit', to='thirdHabit.thirdhabititemdetailtime'),
        ),
    ]
