# Generated by Django 6.0.5 on 2026-08-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdHabit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdhabit',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='thirdhabitdetail',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='thirdhabititem',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='thirdhabititemdetail',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
