# Generated by Django 6.0.5 on 2026-08-09 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thirdHabit', '0002_alter_thirdhabit_create_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thirdhabititem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='thirdhabititemdetail',
            name='author',
        ),
    ]
