# Generated by Django 6.0.5 on 2026-08-09 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thirdHabit', '0003_remove_thirdhabititem_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thirdhabitdetail',
            old_name='schedule',
            new_name='thirdHabit',
        ),
    ]
