# Generated by Django 5.0 on 2025-10-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tododetail',
            name='media_file',
            field=models.ManyToManyField(related_name='media_file_tododetail', to='common.file'),
        ),
    ]
