# Generated by Django 5.0 on 2024-05-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tododetail',
            name='file',
            field=models.ManyToManyField(related_name='file_tododetail', to='common.file'),
        ),
    ]
