# Generated by Django 5.0 on 2024-01-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_update_date_alter_tododetail_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tododetail',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
