# Generated by Django 5.0 on 2024-01-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_author_tododetail_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='tododetail',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
