# Generated by Django 5.0 on 2024-01-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todo_file_tododetail_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='file',
        ),
        migrations.RemoveField(
            model_name='tododetail',
            name='file',
        ),
    ]
