# Generated by Django 5.0 on 2024-01-09 01:39

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_remove_todo_file_remove_tododetail_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododetail',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
