# Generated by Django 5.0 on 2024-01-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_tododetail_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='check_yn',
            field=models.CharField(default='Y', max_length=2),
        ),
        migrations.AddField(
            model_name='todo',
            name='use_yn',
            field=models.CharField(default='Y', max_length=2),
        ),
    ]
