# Generated by Django 5.0 on 2024-01-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_todo_check_yn_todo_use_yn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='check_yn',
            field=models.CharField(default='N', max_length=2),
        ),
    ]
