# Generated by Django 5.0 on 2024-01-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='subject',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
