# Generated by Django 5.0 on 2024-02-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_habit_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='notice_yn',
            field=models.CharField(default='N', max_length=2),
        ),
    ]
