# Generated by Django 5.0 on 2025-10-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_habit_media_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='media_file',
        ),
    ]
