# Generated by Django 5.0 on 2024-02-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_habit_notice_yn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='notice_yn',
            field=models.BooleanField(default=False),
        ),
    ]
