# Generated by Django 5.0 on 2024-02-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('habit', '0004_alter_habit_notice_yn'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='file',
            field=models.ManyToManyField(related_name='file_habit', to='common.file'),
        ),
    ]
