# Generated by Django 5.0 on 2024-02-10 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0005_habit_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='viewcount',
            field=models.ManyToManyField(related_name='viewcount_habit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habit',
            name='voter',
            field=models.ManyToManyField(related_name='voter_habit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habitdetail',
            name='voter',
            field=models.ManyToManyField(related_name='voter_habitdetail', to=settings.AUTH_USER_MODEL),
        ),
    ]
