# Generated by Django 5.1.6 on 2025-03-19 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('mission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='missiondetail',
            old_name='habit',
            new_name='mission',
        ),
        migrations.AlterField(
            model_name='mission',
            name='file',
            field=models.ManyToManyField(related_name='file_mission', to='common.file'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='voter',
            field=models.ManyToManyField(related_name='voter_mission', to=settings.AUTH_USER_MODEL),
        ),
    ]
