# Generated by Django 5.0 on 2025-10-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('mission', '0002_rename_habit_missiondetail_mission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='media_file',
            field=models.ManyToManyField(related_name='media_file_mission', to='common.file'),
        ),
    ]
