# Generated by Django 5.0 on 2025-10-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0003_mission_media_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='media_file',
        ),
    ]
