# Generated by Django 5.0 on 2025-10-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0002_memorization_media_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorization',
            name='media_file',
        ),
    ]
