# Generated by Django 5.0 on 2023-12-27 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_nm', models.CharField(max_length=200)),
                ('study_type', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('use_yn', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('memo', models.DateTimeField()),
                ('study_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meter.studylist')),
            ],
        ),
    ]
