# Generated by Django 5.0 on 2023-12-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0002_rename_study_nm_studylist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='memo',
            field=models.TextField(),
        ),
    ]
