# Generated by Django 5.0 on 2023-12-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0004_alter_studylist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studylist',
            name='use_yn',
            field=models.CharField(default='Y', max_length=2),
        ),
    ]
