# Generated by Django 5.0 on 2024-01-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0006_study_author_studylist_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='studylist',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
