# Generated by Django 5.0 on 2024-01-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0007_studylist_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studylist',
            name='file',
        ),
    ]
