# Generated by Django 5.0 on 2024-01-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0008_remove_studylist_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='studylist',
            name='upload_file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
