# Generated by Django 5.0 on 2024-01-03 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0010_remove_studylist_upload_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='study_list',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='end_date',
            new_name='create_date',
        ),
        migrations.RemoveField(
            model_name='study',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='study',
            name='start_date',
        ),
        migrations.AddField(
            model_name='study',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study',
            name='type',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study',
            name='use_yn',
            field=models.CharField(default='Y', max_length=2),
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('memo', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meter.study')),
            ],
        ),
        migrations.DeleteModel(
            name='StudyList',
        ),
    ]
